


extern "C" fn py_err_occurred() -> PyObjectRef = "PyErr_Occurred";

extern "C" fn py_err_clear() = "PyErr_Clear";
